# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-11-15 07:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import filer.fields.folder
import image_cropping.fields
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0002_auto_20150616_2121'),
        ('filer', '0004_auto_20160328_1434'),
    ]

    operations = [
        migrations.CreateModel(
            name='Loghi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titolo', models.CharField(max_length=100)),
                ('link', models.CharField(blank=True, max_length=250, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='loghi')),
                ('thumb', image_cropping.fields.ImageRatioField('image', '312x135', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=True, verbose_name='312x135')),
                ('miniatura', image_cropping.fields.ImageRatioField('image', '300x300', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=True, verbose_name='300x300')),
            ],
            options={
                'verbose_name_plural': 'Loghi',
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titolo', models.CharField(max_length=100)),
                ('titolo_uk', models.CharField(blank=True, max_length=250, null=True)),
                ('sottotitolo', models.CharField(blank=True, max_length=250, null=True)),
                ('sottotitolo_uk', models.CharField(blank=True, max_length=250, null=True)),
                ('link', models.CharField(blank=True, max_length=250, null=True)),
                ('body', models.TextField(blank=True, null=True, verbose_name='Descrizione')),
                ('body_uk', models.TextField(blank=True, null=True, verbose_name='Descrizione Inglese')),
                ('image', models.ImageField(blank=True, null=True, upload_to='landing')),
                ('cropping', image_cropping.fields.ImageRatioField('image', '500x281', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=True, verbose_name='500x281')),
                ('slidepage', image_cropping.fields.ImageRatioField('image', '870x480', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=True, verbose_name='870x480')),
                ('active', models.BooleanField(default=False, verbose_name='attiva')),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('album', filer.fields.folder.FilerFolderField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='filer.Folder')),
                ('loghi', models.ManyToManyField(blank=True, null=True, to='landing.Loghi', verbose_name='Seleziona Loghi')),
            ],
            options={
                'verbose_name_plural': 'Landing Page',
            },
        ),
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titolo', models.CharField(max_length=100, verbose_name='Titolo')),
                ('titolo_uk', models.CharField(max_length=100, verbose_name='Titolo UK')),
                ('image', models.ImageField(blank=True, null=True, upload_to='slider_landing')),
                ('scritta', models.TextField(blank=True, null=True)),
                ('scritta_uk', models.TextField(blank=True, null=True)),
                ('didascalia', models.TextField(blank=True, null=True)),
                ('didascalia_uk', models.TextField(blank=True, null=True)),
                ('link', models.TextField(blank=True, null=True)),
                ('revolution', image_cropping.fields.ImageRatioField('image', '1170x500', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=True, verbose_name='1170x500')),
                ('slider', image_cropping.fields.ImageRatioField('image', '1920x1280', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=True, verbose_name='1920x1280')),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('active', models.BooleanField(default=False, verbose_name='attiva')),
            ],
            options={
                'ordering': ['id'],
                'verbose_name_plural': 'Slider Landing Page',
            },
        ),
        migrations.AddField(
            model_name='page',
            name='slider',
            field=models.ManyToManyField(blank=True, null=True, to='landing.Slider', verbose_name='Seleziona Immagini Slider'),
        ),
        migrations.AddField(
            model_name='page',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Parole chiave'),
        ),
    ]
