# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-11-15 10:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loghi',
            name='link',
        ),
        migrations.RemoveField(
            model_name='loghi',
            name='thumb',
        ),
    ]
