# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-11-15 11:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0003_auto_20161115_1058'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='album',
        ),
        migrations.RemoveField(
            model_name='page',
            name='body_uk',
        ),
        migrations.RemoveField(
            model_name='page',
            name='cropping',
        ),
        migrations.RemoveField(
            model_name='page',
            name='image',
        ),
        migrations.RemoveField(
            model_name='page',
            name='link',
        ),
        migrations.RemoveField(
            model_name='page',
            name='loghi',
        ),
        migrations.RemoveField(
            model_name='page',
            name='slidepage',
        ),
        migrations.RemoveField(
            model_name='page',
            name='slider',
        ),
        migrations.RemoveField(
            model_name='page',
            name='sottotitolo',
        ),
        migrations.RemoveField(
            model_name='page',
            name='sottotitolo_uk',
        ),
        migrations.RemoveField(
            model_name='page',
            name='titolo_uk',
        ),
    ]
