# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-11-15 11:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0004_auto_20161115_1100'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='loghi',
            field=models.ManyToManyField(blank=True, null=True, to='landing.Loghi', verbose_name='Seleziona Loghi'),
        ),
        migrations.AddField(
            model_name='page',
            name='slider',
            field=models.ManyToManyField(blank=True, null=True, to='landing.Slider', verbose_name='Seleziona Immagini Slider'),
        ),
    ]
