# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-11-16 09:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0006_remove_page_body'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='loghi',
            options={'ordering': ['titolo'], 'verbose_name_plural': 'Loghi'},
        ),
    ]
