# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-01 04:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import filer.fields.folder
import image_cropping.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('filer', '0004_auto_20160328_1434'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fiere',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titolo', models.CharField(max_length=100)),
                ('sottotitolo', models.CharField(blank=True, max_length=250, null=True)),
                ('location', models.CharField(blank=True, max_length=250, null=True)),
                ('body', models.TextField(blank=True, null=True, verbose_name='Descrizione')),
                ('image', models.ImageField(blank=True, null=True, upload_to='fiere')),
                ('cropping', image_cropping.fields.ImageRatioField('image', '500x480', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=True, verbose_name='500x480')),
                ('slidepage', image_cropping.fields.ImageRatioField('image', '870x480', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=True, verbose_name='870x480')),
                ('croppingthumb', image_cropping.fields.ImageRatioField('image', '595x335', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=True, verbose_name='595x335')),
                ('croppingslide', image_cropping.fields.ImageRatioField('image', '1140x487', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=True, verbose_name='1140x487')),
                ('croppingcarousel', image_cropping.fields.ImageRatioField('image', '198x132', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=True, verbose_name='198x132')),
                ('croppingrender', image_cropping.fields.ImageRatioField('image', '1199x674', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=True, verbose_name='1199x674')),
                ('designthumb', image_cropping.fields.ImageRatioField('image', '500x469', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=True, verbose_name='Design Miniatura')),
                ('designbig', image_cropping.fields.ImageRatioField('image', '1200x800', adapt_rotation=False, allow_fullsize=False, free_crop=True, help_text=None, hide_image_field=False, size_warning=True, verbose_name='Design HD')),
                ('designnews', image_cropping.fields.ImageRatioField('image', '1200x1125', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=True, verbose_name='News')),
                ('attiva_slider', models.BooleanField(default=False, verbose_name='attiva in slider')),
                ('active', models.BooleanField(default=False, verbose_name='attiva')),
                ('album', filer.fields.folder.FilerFolderField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='filer.Folder')),
            ],
            options={
                'verbose_name_plural': 'Fiere',
            },
        ),
        migrations.CreateModel(
            name='Showroom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titolo', models.CharField(max_length=100)),
                ('sottotitolo', models.CharField(blank=True, max_length=250, null=True)),
                ('azienda', models.CharField(blank=True, max_length=250, null=True, verbose_name='Azienda')),
                ('location', models.CharField(blank=True, max_length=250, null=True)),
                ('body', models.TextField(blank=True, null=True, verbose_name='Descrizione')),
                ('image', models.ImageField(blank=True, null=True, upload_to='fiere')),
                ('cropping', image_cropping.fields.ImageRatioField('image', '500x480', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=True, verbose_name='500x480')),
                ('slidepage', image_cropping.fields.ImageRatioField('image', '870x480', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=True, verbose_name='870x480')),
                ('croppingthumb', image_cropping.fields.ImageRatioField('image', '595x335', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=True, verbose_name='595x335')),
                ('croppingslide', image_cropping.fields.ImageRatioField('image', '1140x487', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=True, verbose_name='1140x487')),
                ('croppingcarousel', image_cropping.fields.ImageRatioField('image', '198x132', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=True, verbose_name='198x132')),
                ('croppingrender', image_cropping.fields.ImageRatioField('image', '1199x674', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=True, verbose_name='1199x674')),
                ('designthumb', image_cropping.fields.ImageRatioField('image', '500x469', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=True, verbose_name='Design Miniatura')),
                ('designbig', image_cropping.fields.ImageRatioField('image', '1200x800', adapt_rotation=False, allow_fullsize=False, free_crop=True, help_text=None, hide_image_field=False, size_warning=True, verbose_name='Design HD')),
                ('designnews', image_cropping.fields.ImageRatioField('image', '1200x1125', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=True, verbose_name='News')),
                ('planimetria', models.ImageField(blank=True, null=True, upload_to='planimetria')),
                ('planimetria_crop', image_cropping.fields.ImageRatioField('planimetria', '1200x800', adapt_rotation=False, allow_fullsize=False, free_crop=True, help_text=None, hide_image_field=False, size_warning=True, verbose_name='Design HD')),
                ('attiva_slider', models.BooleanField(default=False, verbose_name='attiva in slider')),
                ('active', models.BooleanField(default=False, verbose_name='attiva')),
                ('album', filer.fields.folder.FilerFolderField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='filer.Folder')),
            ],
            options={
                'verbose_name_plural': 'Showroom',
            },
        ),
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titolo', models.CharField(max_length=100, verbose_name='Titolo')),
                ('image', models.ImageField(blank=True, null=True, upload_to='slider')),
                ('scritta', models.TextField(blank=True, null=True)),
                ('didascalia', models.TextField(blank=True, null=True)),
                ('link', models.TextField(blank=True, null=True)),
                ('slider', image_cropping.fields.ImageRatioField('image', '1170x600', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=True, verbose_name='Slider')),
                ('slidepage', image_cropping.fields.ImageRatioField('image', '870x480', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=True, verbose_name='870x480')),
                ('croppingthumb', image_cropping.fields.ImageRatioField('image', '595x335', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=True, verbose_name='595x335')),
                ('croppingslide', image_cropping.fields.ImageRatioField('image', '1140x487', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=True, verbose_name='1140x487')),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('active', models.BooleanField(default=False, verbose_name='attiva')),
            ],
            options={
                'ordering': ['id'],
                'verbose_name_plural': 'Slider',
            },
        ),
        migrations.CreateModel(
            name='Stand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titolo', models.CharField(max_length=100)),
                ('sottotitolo', models.CharField(blank=True, max_length=250, null=True)),
                ('azienda', models.CharField(blank=True, max_length=250, null=True, verbose_name='Azienda')),
                ('location', models.CharField(blank=True, max_length=250, null=True, verbose_name='Location')),
                ('body', models.TextField(blank=True, null=True, verbose_name='Descrizione')),
                ('image', models.ImageField(blank=True, null=True, upload_to='stand')),
                ('cropping', image_cropping.fields.ImageRatioField('image', '500x480', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=True, verbose_name='500x480')),
                ('slidepage', image_cropping.fields.ImageRatioField('image', '870x480', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=True, verbose_name='870x480')),
                ('croppingthumb', image_cropping.fields.ImageRatioField('image', '595x335', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=True, verbose_name='595x335')),
                ('croppingslide', image_cropping.fields.ImageRatioField('image', '1140x487', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=True, verbose_name='1140x487')),
                ('croppingcarousel', image_cropping.fields.ImageRatioField('image', '198x132', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=True, verbose_name='198x132')),
                ('croppingrender', image_cropping.fields.ImageRatioField('image', '1199x674', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=True, verbose_name='1199x674')),
                ('designthumb', image_cropping.fields.ImageRatioField('image', '500x469', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=True, verbose_name='Design Miniatura')),
                ('designbig', image_cropping.fields.ImageRatioField('image', '1200x800', adapt_rotation=False, allow_fullsize=False, free_crop=True, help_text=None, hide_image_field=False, size_warning=True, verbose_name='Design HD')),
                ('designnews', image_cropping.fields.ImageRatioField('image', '1200x1125', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=True, verbose_name='News')),
                ('planimetria', models.ImageField(blank=True, null=True, upload_to='planimetria')),
                ('planimetria_crop', image_cropping.fields.ImageRatioField('planimetria', '1200x800', adapt_rotation=False, allow_fullsize=False, free_crop=True, help_text=None, hide_image_field=False, size_warning=True, verbose_name='Design HD')),
                ('attiva_slider', models.BooleanField(default=False, verbose_name='attiva in slider')),
                ('active', models.BooleanField(default=False, verbose_name='attiva')),
                ('album', filer.fields.folder.FilerFolderField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='filer.Folder')),
                ('fiera', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sito.Fiere')),
            ],
            options={
                'verbose_name_plural': 'Stand',
            },
        ),
    ]
