# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-01 05:58
from __future__ import unicode_literals

from django.db import migrations
import image_cropping.fields


class Migration(migrations.Migration):

    dependencies = [
        ('sito', '0002_auto_20160901_0557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fiere',
            name='cropping',
            field=image_cropping.fields.ImageRatioField('image', '500x281', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=True, verbose_name='500x281'),
        ),
    ]
