# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-12 09:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sito', '0008_auto_20160912_0910'),
    ]

    operations = [
        migrations.AddField(
            model_name='showroom',
            name='link',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
