# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-12 09:54
from __future__ import unicode_literals

from django.db import migrations, models
import image_cropping.fields


class Migration(migrations.Migration):

    dependencies = [
        ('sito', '0010_casehistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titolo', models.CharField(max_length=100)),
                ('body', models.TextField(blank=True, null=True, verbose_name='Descrizione')),
                ('image', models.ImageField(blank=True, null=True, upload_to='gallery')),
                ('cropping', image_cropping.fields.ImageRatioField('image', '500x281', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=True, verbose_name='500x281')),
                ('slidepage', image_cropping.fields.ImageRatioField('image', '870x480', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=True, verbose_name='870x480')),
                ('croppingthumb', image_cropping.fields.ImageRatioField('image', '595x335', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=True, verbose_name='595x335')),
                ('croppingslide', image_cropping.fields.ImageRatioField('image', '1140x487', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=True, verbose_name='1140x487')),
                ('active', models.BooleanField(default=False, verbose_name='attiva')),
            ],
            options={
                'verbose_name_plural': 'Gallery',
            },
        ),
        migrations.AlterField(
            model_name='casehistory',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='casehistory'),
        ),
        migrations.AlterField(
            model_name='showroom',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='showroom'),
        ),
    ]
