# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-18 07:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sito', '0012_auto_20161018_0722'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='province',
            options={'ordering': ['titolo'], 'verbose_name_plural': 'Province'},
        ),
    ]
